apiVersion: v1
kind: Service
metadata:
  name: ai-image-api-service
spec:
  type: NodePort
  selector:
    app: ai-image-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.api.port }}